In [1]:
import numpy as np

In [2]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
print(arr)

[10 20 30 40 50]


In [3]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])

print(matrix)

[[1 2 3]
 [4 5 6]]


In [4]:
print("Shape:", matrix.shape)
print("Size:", matrix.size)
print("Dimensions:", matrix.ndim)
print("Data Type:", matrix.dtype)

Shape: (2, 3)
Size: 6
Dimensions: 2
Data Type: int64


In [5]:
a = np.array([2, 4, 6])
b = np.array([1, 3, 5])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

Addition: [ 3  7 11]
Subtraction: [1 1 1]
Multiplication: [ 2 12 30]
Division: [2.         1.33333333 1.2       ]


In [6]:
arr = np.array([10, 20, 30])

print(arr + 5)
print(arr * 2)

[15 25 35]
[20 40 60]


In [7]:
arr = np.array([10, 20, 30, 40, 50])

print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Maximum:", np.max(arr))
print("Minimum:", np.min(arr))

Sum: 150
Mean: 30.0
Maximum: 50
Minimum: 10


In [8]:
marks = np.array([80, 75, 90, 95, 88])

total = np.sum(marks)
average = np.mean(marks)

print("Total Marks:", total)
print("Average Marks:", average)

Total Marks: 428
Average Marks: 85.6


In [9]:
print(np.zeros((2, 3)))
print(np.ones((2, 2)))
print(np.arange(1, 11))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[ 1  2  3  4  5  6  7  8  9 10]


In [10]:
arr = np.arange(1, 13)

new_arr = arr.reshape(3, 4)

print(new_arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
